"use client"
import React, { useState } from 'react'
import { Lightbulb } from 'lucide-react'
import Image from 'next/image'
import Button from '@/components/CustomButton'

const History = () => {
  // You can replace this with actual history data in the future
  const [userHistory, setuserHistory] = useState([]);

  return (
    <div className='mt-7 rounded-xl border bg-white p-5'>
         <h2 className='text-2xl font-bold mb-2'>Previous History</h2>
        <p className='text-gray-600 mb-6'>
            View your previous interactions and insights generated by our AI tools.
        </p>
    <div className='flex flex-col items-center justify-center min-h-[220px]'>
      {userHistory.length > 0 ? (
        <div>
          {/* Render previous history here */}
        </div>
      ) : (
        <div className="flex flex-col items-center">
        <Image src={'/bulb.svg'} alt='No History' width={100} height={100}/>
          <p className="text-gray-600 font-bold text-lg mb-4 mt-4">You do not have any history yet</p>
          <Button>
            Get Started
          </Button>
        </div>
      )}
    </div>
    </div>
  )
}

export default History

